# Workflow for cpp version of the vending machine
#
# Checks if the project can be compiled without errors. 

name: compile

on: 
  push:
    paths: 
      - 'cpp/*'
      - '.github/workflows/**-cpp.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: List files for compiling
        run : cd cpp && gcc vending_machine.cpp


