# Workflow for cpp version of the vending machine
#
# Checks if the project can be compiled without errors. 

name: compile

on: 
  push:
    paths: 
      - 'python/**'
      - '.github/workflows/**-python.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: install requirements
        working-directory: python/src
        run : pip install -r requirements.txt
      
      - name: Run unit tests using pytest
        working-directory: python/src
        run : pytest


